version: "3.8"
services:
  videoroom:
    image: membraneframework/demo_webrtc_videoroom:latest
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "demo-webrtc-videoroom.membraneframework.org"
      LETSENCRYPT_HOST: "demo-webrtc-videoroom.membraneframework.org"

  nginx-proxy:
    image: jwilder/nginx-proxy:0.8.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-data:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels: 
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.0.2
    restart: unless-stopped
    volumes:
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-data:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: admin+demo@membraneframework.org
      
volumes:
  nginx-certs:
  nginx-vhost:
  nginx-data:
  