name: WebRTC Videoroom - Tag Build
on:
  push:
    tags: 
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push tagged version
        id: docker_build_tag
        uses: docker/build-push-action@v2
        with:
          context: webrtc/videoroom
          file: webrtc/videoroom/Dockerfile
          push: true
          tags: membraneframework/demo_webrtc_videoroom:${{ steps.tag.outputs.tag }}

      - name: Build and push latest version 
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: webrtc/videoroom
          file: webrtc/videoroom/Dockerfile
          push: true
          tags: membraneframework/demo_webrtc_videoroom:latest          
