name: WebRTC Videoroom - Sandbox Build and Deploy
on:
  push:
    branches: 
      - "sandbox"
    paths:
      - "webrtc/videoroom"
      - "!webrtc/videoroom/README.md"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push sandbox version 
        id: docker_build_sandbox
        uses: docker/build-push-action@v2
        with:
          context: webrtc/videoroom
          file: webrtc/videoroom/Dockerfile
          push: true
          tags: membraneframework/demo_webrtc_videoroom:sandbox
      
      - name: Change Docker-Compose tag before deployment
        id: sed_that_compose
        run: sed -i -e "s/latest/sandbox/g" webrtc/videoroom/docker-compose.yml
      
      - name: Change Docker-Compose address before deployment
        id: sed_it_again
        run: sed -i -e "s/demo-/sandbox-/g" webrtc/videoroom/docker-compose.yml

      - name: Deploy to Swarm
        id: deploy
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ${{ secrets.SANDBOX_SWARM_MANAGER }}
          ssh_private_key: ${{ secrets.SSH_PRIV_KEY }}
          ssh_public_key: ${{ secrets.SSH_SERVER_PUBLIC_KEY}}
          args: stack deploy --compose-file webrtc/videoroom/docker-compose.yml videoroom


          